### ISSUE TITLE
Introducing PID in Abbreviations

### ISSUE THREAD

**Issue by wiktorflorian** [PathOS-project/indicator_handbook#16]
Hello,

According to [National Transportation Library](https://transportation.libguides.com/persistent_identifiers/introduction#s-lg-box-21818239), DOI is a type of Persistent Identifier (PID). I think that including PID in abbreviations would be good idea, eventually creating nested expandable structure like:

- PID:
  - DOI
  - PMID
  - etc... 

might also be a good implementation.

Best regards,
Wiktor

**Comment by vtraag** [comment]
Thank you for the suggestion @wiktorflorian! At the moment, the table only includes abbreviations that are in use elsewhere in the handbook. Presumably, PID is not in use, but I'll double check.

**Comment by wiktorflorian** [comment]
I apologize for my limited familiarity with the Open Science Handbook.  It may be advisable to incorporate a PID abbreviation or a section solely dedicated to PIDs, given that more specific IDs such as ORCiD, PIMD, or Handle may inevitably arise in the future. All these IDs can be grouped together as PIDs.

**Comment by vtraag** [comment]
I've decided to remove the abbreviations all together. They were more a legacy of a Word / PDF output type, and the handbook is now really more targeted towards a website format.
