### ISSUE TITLE
Additional indicators for reproducibility?

### ISSUE THREAD

**Issue by vtraag** [PathOS-project/indicator_handbook#26]
It might be possible to add some additional indicators for reproducibility:
- Image manipulation (e.g. see https://doi.org/10.1038/d41586-023-02920-y)
- Detect AI generated text (e.g. "tortured phrases", see https://doi.org/10.1038/d41586-021-02134-0, or more recently https://retractionwatch.com/papers-and-peer-reviews-with-evidence-of-chatgpt-writing/).

**Comment by tklebel** [comment]
Reflecting on these suggestions, they seem to be more relevant to the concept "scientific misconduct", and not reproducibility per se. A good indicator entry for "scientific misconduct" should cover many more aspects (such as undisclosed conflicts of interest, data manipulation, questionable research practices, such as p-hacking, HARKing, etc.). However, this is a very broad topic, and in essence, a topic of its own. 

I therefore think this is out of scope for the reproducibility section.
