### ISSUE TITLE
CI build for site

### ISSUE THREAD

**Issue by vtraag** [PathOS-project/indicator_handbook#45]
In PR #44 we changed the output directory also from `_book` to `_site`. This also requires a change somewhere else in the CI, as the CI currently fails (see https://github.com/PathOS-project/indicator_handbook/actions/runs/9906554179/job/27368339370). 

Unfortunately, this is not something that is directly possible to control from within this repository. @panosgeorgantas Could you make the necessary changes on your end to get this working? Thank you in advance!

**Comment by panosgeorgantas** [comment]
Hello, fixed

**Comment by vtraag** [comment]
Perfect, thanks for the quick response!
