### ISSUE TITLE
Causal intro tidying

### ISSUE THREAD

**Issue by tklebel** [PathOS-project/indicator_handbook#49]
Congrats for getting the intro to finally render in #47 , @vtraag!

I have three minor comments from the live version:

1. I had a hard time finding the intro, although I knew it should be somewhere. It is only listed in the left-side menu below "introduction", where I did not see it for quite a while. Is there any way to make it more findable?
2. Different to our preprint and manuscript, the code of the notebook is visible. This surprised me a bit, but I agree that it is nice to expose the code for reasons of transparency (although some aspects remain "hidden" in other files, such as the simulation or some helper functions). Just wanted to ask whether that was a concious decision. Relatedly, I think the [code folding option](https://quarto.org/docs/output-formats/html-code.html#folding-code) might work nicely here, because it can help with reading flow but still shows code on demand.
3. Lastly, I'm not too keen on the font our theme uses for code. It is not monospaced, and certain code elements look particularly weird (`<-`, `%>%`). Is there an easy way to change that?

**Comment by vtraag** [comment]
> Congrats for getting the intro to finally render in #47 , @vtraag!

Thanks!

> 1. I had a hard time finding the intro, although I knew it should be somewhere. It is only listed in the left-side menu below "introduction", where I did not see it for quite a while. Is there any way to make it more findable?

Yes, happy to include it elsewhere! All sections have their navigation at the left side. Perhaps the "introduction" label make it difficult to find? I thought it would be most fitting there. What would you suggest as an alternative?

> 2. Different to our preprint and manuscript, the code of the notebook is visible. This surprised me a bit, but I agree that it is nice to expose the code for reasons of transparency (although some aspects remain "hidden" in other files, such as the simulation or some helper functions). Just wanted to ask whether that was a concious decision. Relatedly, I think the [code folding option](https://quarto.org/docs/output-formats/html-code.html#folding-code) might work nicely here, because it can help with reading flow but still shows code on demand.

Yes, I only noticed this later. Some of the code should not be shown indeed, and I think only the code that we explicitly want to show. I haven't yet looked at this in detail. If you have suggestions for how to explicitly include code sections that we do want to include and exclude others, let me know!

> 3. Lastly, I'm not too keen on the font our theme uses for code. It is not monospaced, and certain code elements look particularly weird (`<-`, `%>%`). Is there an easy way to change that?

Yes, this needs improvement, but only on some platforms (on Firefox on Ubuntu it looks fine, see below, on my phone not). Not sure why these difference appear, I need to look into it. 

![image](https://github.com/user-attachments/assets/87d750b4-ce22-4030-8655-28d3991aeb37)

There's also some other styling issues still (#15) that should also be corrected.

**Comment by vtraag** [comment]
> Yes, happy to include it elsewhere! All sections have their navigation at the left side. Perhaps the "introduction" label make it difficult to find? I thought it would be most fitting there. What would you suggest as an alternative?

As an update, I've now made a separate "causality" entry (27aeaf3e43680f488e6be7d028568919ff535298) to make it more visible.
